POST https://video-manager-api-dko9.onrender.com/videos
Content-Type: application/json

{
  "title": " Testando rotas",
  "description": "Esse é o primeiro vídeo",
  "duration": 180 
}

###

GET https://video-manager-api-dko9.onrender.com/videos

###

GET https://video-manager-api-dko9.onrender.com/videos/aafbeb66-53a4-4a85-87a9-7584dd5b0df5

###

PUT https://video-manager-api-dko9.onrender.com/videos/755fc26f-ce17-4fe9-8ebd-f14f8ce406c5
Content-Type: application/json

{
  "title": " Teste teste",
  "description": "Esse é um video teste",
  "duration": 180 
}

###

DELETE https://video-manager-api-dko9.onrender.com/videos/755fc26f-ce17-4fe9-8ebd-f14f8ce406c5